package me.tianshili.annotationlib.sensors;

/**
 * @author Elijah Neundorfer 6/17/19
 * @version 6/24/19
 */
public enum SensorDataType {
    ACCELEROMETER,
    ACCELEROMETER_UNCALIBRATED,
    AMBIENT_TEMPERATURE,
    DEVICE_PRIVATE_BASE,
    GAME_ROTATION_VECTOR,
    GEOMAGNETIC_ROTATION,
    GRAVITY,
    GYROSCOPE,
    GYROSCOPE_UNCALIBRATED,
    HEART_BEAT,
    HEART_RATE,
    LIGHT,
    LINEAR_ACCELERATION,
    LOW_LATENCY_OFFBODY_DETECT,
    MAGNETIC_FIELD,
    MAGNETIC_FIELD_UNCALIBRATED,
    MOTION_DETECT,
    POSE_6DOF,
    PRESSURE,
    PROXIMITY,
    RELATIVE_HUMIDITY,
    ROTATION_VECTOR,
    SIGNIFICANT_MOTION,
    STATIONARY_DETECT,
    STEP_COUNTER,
    STEP_DETECTOR,
    RAW_DATA,
    UNKNOWN,
}
