package me.tianshili.annotationlib.network;

public enum SharingTargetType {
    NOT_SHARED_WITH_ANY_EXTERNAL_PARTIES,
    VISIBLE_TO_OTHER_REGISTERED_USERS,
    VISIBLE_TO_THE_PUBLIC,
    SHARED_WITH_AFFILIATES,
    SHARED_WITH_THIRD_PARTIES,
    UNKNOWN
}
