package me.tianshili.annotationlib;

public enum JitNoticeFrequency {
    DO_NOT_SEND_NOTIFICATION,
    SEND_NOTIFICATION_SILENTLY,
    NOTIFICATION_POP_OUT_FIRST_TIME_ONLY,
    NOTIFICATION_ALWAYS_POP_OUT,
    UNKNOWN
}
//
//public enum Transparency {
//    DATA_COLLECTION_IS_EXPLICIT_TO_USERS,
//    DATA_COLLECTION_IS_NOT_OBVIOUS_TO_USERS,
//    UNKNOWN
//}

