package me.tianshili.annotationlib;

public class SourcePurpose {
    public static final int Calendar_CONTEXT_PREDICTION = 1;
    public static final int Calendar_SCHEDULE = 2;
    public static final int Calendar_ALARM = 3;
    public static final int CallLogs_CALL = 4;
    public static final int CallLogs_RECORD_CALL_LOGS = 5;
    public static final int Camera_FLASHLIGHT = 6; //Turn on/off flashlight
    public static final int Camera_VIDEO_STREAMING= 7; //Steam the video capture
    public static final int Camera_CODE_SCANNING = 8; //Scan QR code
    public static final int Camera_DOCUMENT_SCANNING = 9; //Scan document
    public static final int Camera_AUGMENT_REALITY = 10;
    public static final int Camera_VIDEO_RECORDING = 11;
    public static final int Camera_TEXT_RECOGNITION = 12; //Recognize the text in the live video capture
    public static final int Camera_PHOTO_TAKING = 13; //Take photos
    public static final int Contacts_BACKUP_AND_SYNCHRONIZATION = 14;
    public static final int Contacts_CONTACT_MANAGEMENT = 15;
    public static final int Contacts_BLACKLIST = 16;
    public static final int Contacts_CALL_AND_SMS = 17;
    public static final int Contacts_CONTACT_BASED_CUSTOMIZATION = 18;
    public static final int Contacts_EMAIL = 19;
    public static final int Contacts_FIND_FRIENDS = 20;
    public static final int Contacts_RECORD_CONTACTS = 21;
    public static final int Contacts_FAKE_CALLS_AND_SMS = 22;
    public static final int Location_SEARCH_NEARBY_PLACES = 23;
    public static final int Location_PROVIDE_LOCATION_BASED_CONTENT = 24; // merge this with the previous category? Be more specific, like location_based query?
    public static final int Location_TRANSPORTATION_INFORMATION = 25; // tracking trip for apps like uber
    public static final int Location_RECORD_LOCATION = 26; // recording traces?
    public static final int Location_MAP_AND_NAVIGATING = 27;
    public static final int Location_GEOSOCIAL_NETWORKING = 28;
    public static final int Location_GEOTAGGING = 29;
    public static final int Location_LOCATION_SPOOFING = 30;
    public static final int Location_ALERT_AND_REMIND = 31;
    public static final int Location_LOCATION_BASED_GAME = 32;
    public static final int Location_DATA_COLLECTION_FOR_ANALYTICS = 33;
    public static final int Location_DATA_COLLECTION_FOR_ADVERTISING = 34;
    public static final int Microphone_VOICE_AUTHENTICATION = 35; //Authenticate users using voices
    public static final int Microphone_AUDIO_STREAMING = 36; //Make VOIP phone calls
    public static final int Microphone_VOICE_CONTROL = 37; //Use voice to send the command
    public static final int Microphone_SPEECH_RECOGNITION = 38; //Turn the speech audio into text
    public static final int Microphone_AUDIO_RECORDING = 39; //Record voice messages
    public static final int Microphone_ACOUSTIC_EVENT_DETECTION = 40; //Sense users’ health using microphone
    public static final int Microphone_ACOUSTIC_COMMUNICATION = 41; //Decode audios to receive messages
    public static final int Microphone_RECORD_SONGS = 42; //Record songs
    public static final int Sensor_STEP_COUNTER = 43; //Count users' steps
    public static final int Sensor_GAME_INPUT_CONTROLLER = 44; //Detect device movements to control game input
    public static final int Sensor_NAVIGATION_OR_MAP_OR_COMPASS = 45; //Use dead reckoning to improve localization
    public static final int Sensor_SPEAKER_OR_DISPLAY_ACTIVATION = 46; //Turn off screen if the phone is near the users’ ear
    public static final int Sms_SEND_MESSAGES = 47;
    public static final int Sms_ORGANIZE_MESSAGES = 48;
    public static final int Sms_EXTRACT_MESSAGE_CONTENT = 49;
    public static final int Sms_BLOCK_MESSAGES = 50;
    public static final int Sms_SCHEDULE_MESSAGES = 51;
    public static final int Sms_BACK_UP_OR_SYNC_MESSAGES = 52;
    public static final int UniqueId_TRACKING_DATA_COLLECTED_WITHIN_APP = 53;
    public static final int UniqueId_TRACKING_DATA_COLLECTED_FROM_OTHER_APPS = 54;
    public static final int UniqueId_HANDLE_MULTIPLE_INSTALLS = 55;
    public static final int UniqueId_ENFORCING_FREE_CONTENT_LIMITS = 56;
    public static final int UniqueId_MANAGING_TELEPHONY_AND_CARRIER_FUNCTIONALITY = 57;
    public static final int UniqueId_IDENTIFYING_BOTS_AND_DDOS_ATTACKS = 58; // In this case, you are trying to detect multiple fake devices attacking your backend services.
    public static final int UniqueId_DETECTING_HIGH_VALUE_STOLEN_CREDENTIALS = 59; // In this case, you are trying to detect if a single device is being used multiple times with high-value, stolen credentials (e.g. to make fraudulent payments)
    public static final int UserFile_ACCESS_PHOTO_ALBUM = 60;
    public static final int UserFile_MANAGE_DOWNLOADED_FILES = 61;
    public static final int UserFile_APP_DATA_PERSISTENT_STORAGE = 62;
    public static final int UserInput_ACCOUNT_REGISTRATION = 63;
    public static final int UserInput_ACCOUNT_AUTHENTICATION = 64;
    public static final int UserInput_WRITE_POSTS_OR_COMMENTS = 65;
    public static final int UserInput_ENTER_SEARCH_TERMS = 66;
    public static final int UserInput_ENTER_FILE_NAMES = 67;
}
