package me.tianshili.annotationlib.privacynotice;

public enum PrivacyNoticeType {
    PRIVACY_POLICY,
    DATA_USE_USER_CONSENT_DIALOG,
    DATA_USE_PARENTAL_CONSENT_DIALOG,
    DATA_USE_PURPOSE_EXPLANATION,
    DATA_SHARING_DETAILS,
    DATA_RETENTION_DETAILS,
    SHOW_PAST_COLLECTED_DATA,
    UNKNOWN
}
